version: '3'
services:
  elasticsearch:
    image: elasticsearch:7.0.1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPT=-Xms1g -Xmx1g"
      - discovery.type=single-node
    ports:
      - "9300:9300"
      - "9200:9200"
  kibana:
    image: kibana:7.0.1
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - XPACK_SECURITY_ENABLED=true
    ports:
      - "5601:5601"
    volumes:
      - $PWD/kibana.yml:/usr/share/kibana/config/kibana.yml
volumes:
  esdata:
