apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: kube-log
  labels:
    app: grafana
spec:
  selector:
    app: grafana
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30300
  type: NodePort
