apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: grafana
  name: grafana
  namespace: kube-log
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      volumes:
      - name: grafana-pvc
        persistentVolumeClaim:
          claimName: grafana-pvc
      containers:
      - name: grafana
        image: grafana/grafana:6.2.0-beta2
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
        env:
          # NOTE: the cluster name; update this
          - name: GF_PATHS_CONFIG
            value: /var/lib/grafana/grafana.ini
        resources:
          limits:
            cpu: 500m
            memory: 2500Mi
          requests:
            cpu: 100m
            memory: 100Mi
        # livenessProbe:
        #   exec:
        #     command:
        #       - wget 
        #       - localhost:3000
        #       - --spider
        #   initialDelaySeconds: 30
        #   periodSeconds: 30
        # readinessProbe:
        #   exec:
        #     command:
        #       - wget 
        #       - localhost:3000
        #       - --spider
          # initialDelaySeconds: 120
          # periodSeconds: 5
        volumeMounts:
        - mountPath: /var/lib/grafana
          name: grafana-pvc
