apiVersion: v1
kind: ConfigMap
metadata:
  name: blackbox-exporter-conf
  namespace: kube-log
  labels:
    name: blackbox-exporter-conf
data:
  config.yml: |-
    modules:
      http_2xx:
        prober: http
        timeout: 5s
        http:
          valid_http_versions: ["HTTP/1.1", "HTTP/2"]
          valid_status_codes: []  # Defaults to 2xx
          method: GET
          no_follow_redirects: false
          fail_if_ssl: false
          fail_if_not_ssl: false
          fail_if_body_matches_regexp:
            - "Failed to connect"
          fail_if_body_not_matches_regexp:
            - '\d{10}'      # 对应/health的10位数字时间戳
          tls_config:
            insecure_skip_verify: false
          preferred_ip_protocol: "ip4" # defaults to "ip6"
