version: "3"
networks:
  prometheus-network:
    driver: bridge
services:
  prometheus:
    image: prom/prometheus:latest
    ports:
      - 9090:9090
    volumes:
      - $PWD/prometheus.yml:/etc/prometheus/prometheus.yml
  blackbox:
    image: prom/blackbox-exporter:latest
    privileged: true
    volumes:
      - $PWD/blackbox.yml:/etc/blackbox_exporter/config.yml
    ports:
      - '9115:9115'    
  grafana:
    image: grafana/grafana:latest
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=smu.P@ssw0rd
      - GF_PATHS_CONFIG=/var/lib/grafana/grafana.ini
      # - GF_SERVER_ROOT_URL=http://monitor.shmtu.edu.cn
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - $PWD/grafana:/var/lib/grafana
