apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
data:
  fluentd.conf: |
    <source>
      type tail
      format none
      path /var/log/1.log
      pos_file /var/log/1.log.pos
      tag count.format1
    </source>

    <match haproxy.**>
      @type copy
      <store>
        @type elasticsearch
        host elasticsearch
        port 9200
        logstash_format true
        index_name haproxy
        type_name haproxy
        <buffer>
          flush_mode interval
          flush_thread_count 4
          flush_interval 5s
          chunk_limit_size 2M
          queue_limit_length 8
        </buffer>
      </store>
      <store>
        @type stdout
      </store>
    </match>

