apiVersion: v1
kind: PersistentVolume
metadata:
  name: gfs-pv-drupal
spec:
  capacity: 
    storage: 40Gi
  accessModes:
    - ReadWriteMany
  glusterfs:
    endpoints: "glusterfs-cluster"
    path: "drupal-www"
    readOnly: false
