apiVersion: v1
kind: Service
metadata:
  name: glusterfs-cluster
spec:
  ports:
  - port: 1
---
kind: Endpoints
apiVersion: v1
metadata:
  name: glusterfs-cluster
subsets:
- addresses:
  - ip: 10.81.250.11
  ports:
  - port: 1
- addresses:
  - ip: 10.81.250.12
  ports:
  - port: 1
- addresses:
  - ip: 10.81.250.13
  ports:
  - port: 1
