apiVersion: v1
kind: Service
metadata:
  name: prometheus-blackbox-exporter
  namespace: kube-log
  labels:
    app: prometheus-blackbox-exporter
spec:
  selector:
    app: prometheus-blackbox-exporter
  ports:
  - port: 9115
    name: transport
  clusterIP: None
