version: "3"
services:
  nexus:
    image: sonatype/nexus3:latest
    deploy:
      restart_policy: 
        condition: on-failure
    ports:
      - "8081:8081"
      - "8082:8082"
      - "8083:8083"
    volumes:
      - /data/nexus-data:/nexus-data
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
      - "8443:8443"
    volumes:
      - /data/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /data/nginx/shmtu.crt:/etc/nginx/shmtu.crt
      - /data/nginx/shmtu.key:/etc/nginx/shmtu.key
