apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc-test
  labels:
    app: test
spec:
  storageClassName: nfs-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
