apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-master
  namespace: kube-log
  labels:
    service: elasticsearch
    role: master
spec:
  selector:
    service: elasticsearch
    role: master
  ports:
  - port: 9300
    name: transport
  clusterIP: None
