apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  namespace: kube-log
  name: elasticsearch-master
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      service: elasticsearch
      role: master
