apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: kube-log
  labels:
    service: elasticsearch
    role: data
spec:
  selector:
    service: elasticsearch
    role: data
  ports:
  - port: 9200
    targetPort: 9200
    nodePort: 30200
  type: NodePort
